# calculator-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
        - name: calculator
          image: yourdockerhub/calculator:latest  # build & push first
          ports:
            - containerPort: 3001
          env:
            - name: MONGO_URL
              value: "mongodb://calcuser:calcpass@mongodb:27017/calculatorDB?authSource=admin"
---
apiVersion: v1
kind: Service
metadata:
  name: calculator-service
spec:
  selector:
    app: calculator
  ports:
    - port: 3001
      targetPort: 3001
