apiVersion: v1  # Specifies the API version for the PersistentVolume resource
kind: PersistentVolume  # Declares this resource as a PersistentVolume (PV)
metadata:
  name: mongo-pv  # Name of the PersistentVolume
spec:
  capacity:
    storage: 1Gi  # Sets the storage capacity to 1Gi (1 gigabyte)
  accessModes:
    - ReadWriteOnce  # Allows the volume to be mounted as read-write by a single node
  hostPath:
    path: "/data/mongo"  # Path on the host node’s filesystem (used in local clusters like Minikube)
---
apiVersion: v1  # Specifies the API version for the PersistentVolumeClaim resource
kind: PersistentVolumeClaim  # Declares this resource as a PersistentVolumeClaim (PVC)
metadata:
  name: mongo-pvc  # Name of the PersistentVolumeClaim
spec:
  accessModes:
    - ReadWriteOnce  # Requests a volume that can be mounted read-write by one node
  resources:
    requests:
      storage: 1Gi  # Requests 1Gi of storage from the matched PersistentVolume
