apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-root-username: cm9vdA==        # base64 for 'root'
  mongo-root-password: cGFzc3dvcmQ=    # base64 for 'password'
  mongo-app-username: Y2FsY1VzZXI=     # base64 for 'calcUser'
  mongo-app-password: Y2FsY1Bhc3M=     # base64 for 'calcPass'
