apiVersion: v1
kind: Service
metadata:
  name: calculator-service
spec:
  selector:
    app: calculator
  ports:
    - protocol: TCP
      port: 3009           # This is the port you'll forward to
      targetPort: 3009     # This must match your container's exposed port
